# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- rvm install 2.2.2
- rvm use 2.2.2
- gem install cocoapods
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/MaterialDesignSpinner.xcworkspace -scheme MaterialDesignSpinner-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
